spring.application.name=inventory_backend
server.port=8080

# ===============================
# CONFIGURACIÓN DE LA BASE DE DATOS (MariaDB)
# ===============================
spring.datasource.url=${DB_URL_LOCAL:jdbc:mariadb://localhost:3307/inventory_db}
spring.datasource.username=${DB_USER:unpa_user}
spring.datasource.password=${DB_PASSWORD:unpa_password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# "validate" es vital porque Liquibase será el encargado de crear/modificar las tablas.
spring.jpa.hibernate.ddl-auto=validate
# Muestra las consultas SQL en la consola
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
# JWT
app.jwt.secret=${JWT_SECRET:m3qlDk9pXrWvYz2BcNhFgTsJ7KuEaL5e8P0QiV6oCbRAjHwGdnUxMy}
# 24 horas
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200}