spring.application.name=inventory_backend
server.port=8080

# ===============================
# CONFIGURACIÓN DE LA BASE DE DATOS (MariaDB)
# ===============================
# Usamos localhost:3307
spring.datasource.url=jdbc:mariadb://localhost:3307/inventory_db
spring.datasource.username=unpa_user
spring.datasource.password=unpa_password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
# "validate" es vital porque Liquibase será el encargado de crear/modificar las tablas.
spring.jpa.hibernate.ddl-auto=validate
# Muestra las consultas SQL en la consola (útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true